### ISSUE TITLE
Apache Script

### ISSUE THREAD

**Issue by stevemcilwain** [stevemcilwain/Disposable-Kali#1]
Add a script to enable and start Apache, such as:

systemctl enable Apache2
systemctl start Apache2

Perhaps also delete any existing files in /var/www/html and any Apache security hardening.

Alternately could spin up a python http server, since this is really just for hosting tools to transfer to target systems.

**Comment by tnkr** [comment]
much easier to just launch `python3 -m http.server` in the folder you want to host. Apache's overhead and need to take it up and down is just unneeded extra steps.
